- include: update_apt_via_module.yml
- include: update_yum_via_module.yml
- name: gem -> prerequisites -> apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    # For all gems
    - ruby
    - ruby-dev
    # For native gems
    - build-essential
    - patch
    ## For nokogiri
    - zlib1g-dev
    - liblzma-dev
    - libgmp-dev
    ## For pg
    - libpq-dev
- name: gem -> prerequisites -> yum
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
    loop:
      # TODO
- name: gem -> install all our packages
  become: yes
  become_user: root
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
  loop:
    # nokogiri: Parser for HTML and XML
    - nokogiri
    # pg: PostgreSQL interface for Ruby
    - pg
    # rails: Ruby on Rails web framework
    - rails
    # rake: a make-like build utility
    - rake
  