- name: Update yum via command
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  command: "yum --quiet --assumeyes {{ item }}"
  loop:
    - "clean"
    - "--obsolete update"
    - "clean"
