- name: Update yum
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  yum:
    name: '*'
    state: latest
    update_cache: yes
    upgrade: full
    autoremove: yes
    purge: yes
